### ISSUE TITLE
Inconsistent behavior with (n, ) and (n,1) function output

### ISSUE THREAD

**Issue by gtpash** [prmiles/pyfod#22]
**Describe the bug**
Quadrature routines do not perform element-wise multiplication when computing the terms in the quadrature sum.

**To Reproduce**
1. def f1(t): 
         return np.exp(t).reshape(t.size, )
2. def f2(t): 
         return np.exp(t).reshape(t.size, 1)
3. Evaluating the integral with f1 and f2 do not return same quantity

**Expected behavior**
Integration of f1 and f2 return the same value.

**Screenshots**

**Desktop (please complete the following information):**
 - Version 0.1.0

**Comment by prmiles** [comment]
Issue resolved in #23
