### ISSUE TITLE
Error in Caputo tutorial equation

### ISSUE THREAD

**Issue by prmiles** [prmiles/pyfod#32]
**Describe the bug**
The second equation in the Caputo tutorial appears to be missing an integration step.

https://nbviewer.jupyter.org/github/prmiles/pyfod/blob/master/tutorials/caputo.ipynb

The final expression needs to integrate over s.

**Comment by prmiles** [comment]
@gtpash Can you confirm that this is an error?

**Comment by gtpash** [comment]
@prmiles I believe you are correct. In practice we evaluate ![\int_{t_0}^{t_j} \frac{1}{(t_j-s)^{\alpha}} ds](https://render.githubusercontent.com/render/math?math=%5Cint_%7Bt_0%7D%5E%7Bt_j%7D%20%5Cfrac%7B1%7D%7B(t_j-s)%5E%7B%5Calpha%7D%7D%20ds) analytically, but in the equation, we haven't carried out that step yet.
